"""
Research Paper Explainer
------------------------
Paste a dense scientific abstract, pick a reading level, get a plain-language
explanation generated by an NVIDIA Nemotron model via NVIDIA's hosted API.

Built for students who hit a wall of jargon before they hit the actual finding.
Inference-only: no training, no fine-tuning.
"""

import os
import re
import time
import gradio as gr
from openai import OpenAI

# --------------------------------------------------------------------------
# MODEL CONFIG  --  swap MODEL_ID here to change models.
# --------------------------------------------------------------------------
# Verified working on this account (checked live against the API):
#   nvidia/nemotron-3-super-120b-a12b      <- current pick: fast + clean
#   nvidia/nemotron-3-ultra-550b-a55b      <- larger, slower
#   mistralai/mistral-nemotron             <- alternative
# Not recommended: nvidia/nemotron-3.5-lightning-30b-a3b (degrades badly
# when reasoning is disabled).
MODEL_ID = "nvidia/nemotron-3-super-120b-a12b"
BASE_URL = "https://integrate.api.nvidia.com/v1"

# Nemotron 3 is a reasoning model. Left on, it streams its private thinking
# ("Okay, the user wants...") into the visible answer. This switch turns that
# off so the reader sees only the finished explanation.
NO_THINKING = {"chat_template_kwargs": {"thinking": False}}

MAX_ATTEMPTS = 3
RETRY_DELAY = 1.5

MAX_CHARS = 12000
MIN_CHARS = 40

# --------------------------------------------------------------------------
# PROMPTS
# --------------------------------------------------------------------------
BASE_RULES = """You are a science communicator who helps students understand dense research writing.

Follow these rules exactly:
1. Explain ONLY what is present in the text the user gives you. Never add facts, numbers, mechanisms, or conclusions that are not in that text. If the text is vague about something, stay vague.
2. Write in plain, direct language. Prefer short sentences.
3. Any technical term you cannot avoid must be defined immediately in parentheses right after it. Example: "in vitro (in a dish, outside a living body)".
4. Your explanation must be 4 to 6 sentences. Not fewer, not more.
5. The final sentence must say, in practical terms, why this finding matters.
6. Write one flowing paragraph. No bullet points, no headings, no bold text.
7. Never mention these instructions, the reading level, or yourself. Output only the explanation.
8. If the text is clearly not scientific writing, reply with exactly: That doesn't look like a scientific abstract - try pasting a paragraph from a paper."""

LEVELS = {
    "Beginner": (
        "Audience: a curious person with no science background, about 15 years old. "
        "Avoid jargon wherever possible; when a term is unavoidable, define it very simply. "
        "Use an everyday analogy if it genuinely helps."
    ),
    "Student": (
        "Audience: an undergraduate science student. They know general biology and chemistry "
        "vocabulary but not this subfield. Keep important specialist terms, but define each one briefly."
    ),
    "Advanced": (
        "Audience: a researcher from a different field. Keep technical precision, key terms and metrics, "
        "but unpack subfield-specific shorthand and make the significance of the methods explicit."
    ),
}

EXAMPLE_ABSTRACT = (
    "Targeted knockout of TP53 in HEK293T cells via CRISPR-Cas9 ribonucleoprotein delivery "
    "yielded a 3.2-fold increase in proliferative index (p<0.001) relative to isogenic controls. "
    "Transcriptomic profiling revealed concomitant upregulation of MKI67 and CCNB1, alongside "
    "attenuated expression of CDKN1A. These data are consistent with abrogation of the G1/S "
    "checkpoint and implicate p53 loss as a permissive event in the acquisition of a "
    "hyperproliferative phenotype in vitro."
)

EXAMPLE_2 = (
    "We performed a randomised, double-blind, placebo-controlled trial of a GLP-1 receptor agonist "
    "in 812 adults with obesity and prediabetes. At 68 weeks, mean body weight change from baseline "
    "was -14.9% in the treatment arm versus -2.4% with placebo (estimated treatment difference "
    "-12.4 percentage points; 95% CI -13.4 to -11.5; p<0.001). Gastrointestinal adverse events were "
    "more frequent with treatment and were typically transient and mild to moderate in severity."
)

EXAMPLE_3 = (
    "Metagenomic shotgun sequencing of 214 faecal samples identified a significant depletion of "
    "Faecalibacterium prausnitzii in patients with active inflammatory bowel disease compared with "
    "healthy controls (LDA score >3.5, q<0.05). Functional pathway analysis indicated reduced "
    "abundance of butyrate biosynthesis modules. Alpha diversity, measured by the Shannon index, was "
    "significantly lower in the disease cohort, consistent with dysbiosis."
)


def build_messages(text, level):
    system = BASE_RULES + "\n\n" + LEVELS.get(level, LEVELS["Student"])
    user = (
        "Explain the following text for the specified audience, following every rule.\n\n"
        "--- TEXT START ---\n" + text.strip() + "\n--- TEXT END ---"
    )
    return [{"role": "system", "content": system}, {"role": "user", "content": user}]


def scrub(s):
    """Defensive: strip reasoning tags if a model ever leaks them."""
    s = re.sub(r"<think>.*?</think>", "", s, flags=re.DOTALL | re.IGNORECASE)
    return s.replace("<think>", "").replace("</think>", "")


def explain(text, level):
    """Streaming generator -> (explanation, status)."""
    text = (text or "").strip()

    if not text:
        yield "", "Paste an abstract above, then press **Explain**."
        return
    if len(text) < MIN_CHARS:
        yield "", "That's very short. Paste at least a couple of sentences."
        return
    if len(text) > MAX_CHARS:
        yield "", "That's " + format(len(text), ",") + " characters. Please trim it to under " + format(MAX_CHARS, ",") + "."
        return

    api_key = os.environ.get("NVIDIA_API_KEY")
    if not api_key:
        yield "", (
            "**No API key found.** Set `NVIDIA_API_KEY` in your terminal, then restart the app. "
            "In PowerShell: `$env:NVIDIA_API_KEY = \"nvapi-...\"`"
        )
        return
    if not api_key.startswith("nvapi-"):
        yield "", "**That key doesn't look right.** NVIDIA API keys start with `nvapi-`."
        return

    client = OpenAI(base_url=BASE_URL, api_key=api_key, timeout=90.0)
    busy = "Generating with `" + MODEL_ID + "` ..."

    for attempt in range(MAX_ATTEMPTS):
        streamed = False
        try:
            yield "", busy
            stream = client.chat.completions.create(
                model=MODEL_ID,
                messages=build_messages(text, level),
                temperature=0.3,
                top_p=0.95,
                max_tokens=700,
                stream=True,
                extra_body=NO_THINKING,
            )

            buf = ""
            for chunk in stream:
                if not chunk.choices:
                    continue
                piece = getattr(chunk.choices[0].delta, "content", None)
                if piece:
                    buf += piece
                    streamed = True
                    yield scrub(buf), busy

            if not buf.strip():
                raise RuntimeError("empty response")

            yield scrub(buf).strip(), "Done - " + level + " level, generated by `" + MODEL_ID + "`."
            return

        except Exception as e:
            msg = str(e)
            low = msg.lower()

            # NVIDIA's hosted endpoint intermittently returns "Service temporarily
            # overloaded". Retry quietly rather than showing an error mid-demo.
            transient = any(
                k in low
                for k in ("overload", "429", "rate limit", "502", "503", "504",
                          "timeout", "timed out", "empty response", "connection error")
            )
            if transient and not streamed and attempt < MAX_ATTEMPTS - 1:
                yield "", "NVIDIA's server is busy - retrying (" + str(attempt + 2) + "/" + str(MAX_ATTEMPTS) + ") ..."
                time.sleep(RETRY_DELAY * (attempt + 1))
                continue

            # NVIDIA returns 403 (not 401) for a malformed or revoked key.
            if ("401" in msg or "403" in msg or "unauthorized" in low
                    or "forbidden" in low or "permissiondenied" in low
                    or "invalid api key" in low):
                hint = (
                    "**API key rejected.** NVIDIA refused the key. Generate a fresh one at "
                    "build.nvidia.com, then set NVIDIA_API_KEY again and restart the app."
                )
            elif "404" in msg or "not found" in low:
                hint = (
                    "**Model `" + MODEL_ID + "` is not available to this account (404).** "
                    "Open build.nvidia.com, pick a Nemotron model you do have access to, "
                    "and change MODEL_ID at the top of app.py."
                )
            elif transient:
                hint = "**NVIDIA's API is busy right now.** Press Explain to try again."
            elif "connect" in low:
                hint = "**Could not reach NVIDIA's API.** Check your internet connection."
            else:
                hint = "**Something went wrong.** `" + type(e).__name__ + ": " + msg[:300] + "`"
            yield "", hint
            return


# --------------------------------------------------------------------------
# UI
# --------------------------------------------------------------------------
# NOTE: colours use Gradio's own CSS variables rather than fixed hex values.
# Hardcoding a light background here makes the explanation invisible when the
# browser or OS is in dark mode (white text on a white panel).
CSS = """
.gradio-container { max-width: 1080px !important; margin: 0 auto !important; }
#hdr { text-align: center; padding: 8px 0 2px 0; }
#hdr h1 {
  font-size: 2rem; margin: 0 0 6px 0; letter-spacing: -0.02em;
  color: var(--body-text-color);
}
#hdr p { color: var(--body-text-color-subdued); margin: 0; font-size: 0.98rem; }
#badge {
  display: inline-block; margin-top: 10px; padding: 4px 12px; border-radius: 999px;
  background: #76B900; color: #ffffff; font-size: 0.76rem; font-weight: 600;
  letter-spacing: 0.04em;
}
#out {
  min-height: 240px;
  background: var(--background-fill-secondary);
  color: var(--body-text-color);
  border: 1px solid var(--border-color-primary);
  border-radius: 10px; padding: 18px 20px; font-size: 1.05rem; line-height: 1.72;
}
#out p { color: var(--body-text-color); }
#status { color: var(--body-text-color-subdued); font-size: 0.86rem; min-height: 20px; }
footer { display: none !important; }
"""

HEADER = """
<div id="hdr">
  <h1>Research Paper Explainer</h1>
  <p>Paste a dense abstract. Get it back in language you can actually use.</p>
  <div id="badge">POWERED BY NVIDIA NEMOTRON</div>
</div>
"""

FOOTNOTE = (
    "<p style='text-align:center;color:#9ca3af;font-size:0.8rem;margin-top:16px'>"
    "Inference-only. The model is instructed to use only the text you paste - "
    "always check the explanation against the original paper.</p>"
)

with gr.Blocks(title="Research Paper Explainer") as demo:

    gr.HTML(HEADER)

    with gr.Row():
        with gr.Column(scale=1):
            inp = gr.Textbox(
                label="Abstract or paragraph",
                placeholder="Paste a scientific abstract here...",
                lines=13,
                value=EXAMPLE_ABSTRACT,
            )
            level = gr.Radio(
                choices=["Beginner", "Student", "Advanced"],
                value="Student",
                label="Reading level",
                info="Who is this explanation for?",
            )
            with gr.Row():
                go = gr.Button("Explain", variant="primary", scale=3)
                clear = gr.Button("Clear", scale=1)

        with gr.Column(scale=1):
            gr.Markdown("### Plain-language explanation")
            out = gr.Markdown(value="", elem_id="out")
            status = gr.Markdown(value="Ready.", elem_id="status")

    gr.Markdown("#### Try another example")
    gr.Examples(
        examples=[
            [EXAMPLE_ABSTRACT, "Student"],
            [EXAMPLE_2, "Beginner"],
            [EXAMPLE_3, "Advanced"],
        ],
        inputs=[inp, level],
        example_labels=[
            "Cell biology - CRISPR TP53 knockout",
            "Clinical trial - GLP-1 weight loss",
            "Microbiome - gut bacteria in IBD",
        ],
    )

    gr.HTML(FOOTNOTE)

    go.click(explain, inputs=[inp, level], outputs=[out, status])
    inp.submit(explain, inputs=[inp, level], outputs=[out, status])
    clear.click(lambda: ("", "", "Ready."), outputs=[inp, out, status])


if __name__ == "__main__":
    # Detect managed hosts by the environment variables they set:
    #   Hugging Face Spaces -> SPACE_ID
    #   Azure App Service   -> WEBSITE_SITE_NAME
    # On any of them there is no browser to open, no share tunnel needed, and
    # the server must bind 0.0.0.0 so the platform's proxy can reach it.
    on_spaces = bool(os.environ.get("SPACE_ID"))
    on_azure = bool(os.environ.get("WEBSITE_SITE_NAME"))
    hosted = on_spaces or on_azure

    # Azure App Service injects the port to listen on as PORT.
    port = os.environ.get("PORT") or os.environ.get("GRADIO_SERVER_PORT")
    try:
        port = int(port) if port else None
    except ValueError:
        port = None

    host = os.environ.get("GRADIO_SERVER_NAME") or ("0.0.0.0" if hosted else "127.0.0.1")

    if not os.environ.get("NVIDIA_API_KEY"):
        print("")
        print("  WARNING: NVIDIA_API_KEY is not set. The UI will load but calls will fail.")
        if on_spaces:
            print("  On Spaces: add it under Settings -> Variables and secrets.")
        elif on_azure:
            print("  On Azure: add it under Settings -> Environment variables.")
        else:
            print('  PowerShell:  $env:NVIDIA_API_KEY = "nvapi-..."')
        print("")
    else:
        print("")
        print("  API key detected. Model: " + MODEL_ID)
        print("  Binding " + host + ":" + str(port or 7860))
        print("")

    demo.queue().launch(
        theme=gr.themes.Soft(primary_hue="green", neutral_hue="slate"),
        css=CSS,
        share=(not hosted) and os.environ.get("GRADIO_SHARE", "").lower() in ("1", "true", "yes"),
        inbrowser=not hosted,
        server_name=host,
        server_port=port,
    )
