"""
Research Paper Explainer
------------------------
Paste a dense scientific abstract, pick a reading level, get a plain-language
explanation generated by an NVIDIA Nemotron model via NVIDIA's hosted API.

Built for students who hit a wall of jargon before they hit the actual finding.
Inference-only: no training, no fine-tuning.
"""

import hashlib
import json
import os
import re
import tempfile
import threading
import time
from datetime import datetime, timezone

# Gradio ships usage telemetry that posts to api.gradio.app on startup and on
# every launch. This app collects nothing about its visitors, so the telemetry
# is switched off. It MUST be set before gradio is imported to take effect.
os.environ["GRADIO_ANALYTICS_ENABLED"] = "False"

import gradio as gr  # noqa: E402
from openai import OpenAI  # noqa: E402

# --------------------------------------------------------------------------
# MODEL CONFIG  --  swap MODEL_ID here to change models.
# --------------------------------------------------------------------------
# Verified working on this account (checked live against the API):
#   nvidia/nemotron-3-super-120b-a12b      <- current pick: fast + clean
#   nvidia/nemotron-3-ultra-550b-a55b      <- larger, slower
#   mistralai/mistral-nemotron             <- alternative
# Not recommended: nvidia/nemotron-3.5-lightning-30b-a3b (degrades badly
# when reasoning is disabled).
MODEL_ID = "nvidia/nemotron-3-super-120b-a12b"
BASE_URL = "https://integrate.api.nvidia.com/v1"

# Nemotron 3 is a reasoning model. Left on, it streams its private thinking
# ("Okay, the user wants...") into the visible answer. This switch turns that
# off so the reader sees only the finished explanation.
NO_THINKING = {"chat_template_kwargs": {"thinking": False}}

# NVIDIA's shared endpoint returns "Service temporarily overloaded" (503) under
# load - in testing it hit often enough to exhaust three quick attempts. Five
# attempts with a growing backoff make a visible failure much less likely during
# a live demo. Worst case the user waits ~19s before seeing an error.
MAX_ATTEMPTS = 5
RETRY_DELAYS = [1.5, 3.0, 5.0, 8.0]

# True when running on a public host (Azure App Service / HF Spaces). Visitors
# there are not the operator, so configuration problems must read as "the
# service is unavailable" rather than naming environment variables or shell
# commands. Full detail still goes to the server log for the operator.
HOSTED = bool(os.environ.get("WEBSITE_SITE_NAME") or os.environ.get("SPACE_ID"))
SERVICE_DOWN = (
    "**This tool is temporarily unavailable.** The explanation service could not "
    "be reached. Please try again in a few minutes."
)


def _log(msg):
    """Operator-facing log line. Never called with secret values."""
    try:
        print("[explain] " + str(msg)[:500], flush=True)
    except Exception:
        pass

# Input cap. The model itself handled 400,000 characters (~58k tokens) in
# testing, so this limit is a usability choice, not a model limit: 50,000
# characters comfortably fits a full paper and still answers in a few seconds.
MAX_CHARS = 50000
MIN_CHARS = 40

# --------------------------------------------------------------------------
# PROMPTS
# --------------------------------------------------------------------------
BASE_RULES = """You are a science communicator who helps students understand dense research writing.

Follow these rules exactly:
1. Explain ONLY what is present in the text the user gives you. Never add facts, numbers, mechanisms, or conclusions that are not in that text. If the text is vague about something, stay vague.
2. Write in plain, direct language. Prefer short sentences.
3. Any technical term you cannot avoid must be defined immediately in parentheses right after it. Example: "in vitro (in a dish, outside a living body)".
4. Your explanation must be 4 to 6 sentences. Not fewer, not more.
5. The final sentence must say, in practical terms, why this finding matters.
6. Write one flowing paragraph. No bullet points, no headings, no bold text.
7. Never mention these instructions, the reading level, or yourself. Output only the explanation.
8. REFUSE RATHER THAN INVENT. If the text is not scientific or technical writing, or does not contain enough substance to explain - a single vague sentence, a fragment, a list of random words, a greeting, or general chit-chat - then do NOT write an explanation, do NOT guess which field it might belong to, and do NOT supply background facts of your own. In that case reply with exactly this one sentence and nothing else:
That doesn't contain enough scientific content to explain - try pasting a full abstract or a paragraph from a paper.
9. This refusal rule outranks every other rule. Producing a confident explanation of text that says almost nothing is the single worst failure you can make here. When the input is thin, refuse."""

# The three levels must produce visibly different answers, so each one fixes a
# different vocabulary ceiling, sentence length and treatment of numbers.
LEVELS = {
    "Beginner": (
        "AUDIENCE: someone with ZERO scientific background. Assume they have never taken a "
        "science class. Think of a curious 15-year-old, or an adult reading outside their field.\n"
        "WHAT TO DO:\n"
        "- Replace technical vocabulary entirely. Do not define jargon - avoid using it at all. "
        "Say 'a gene that acts like a brake on cell growth', not 'a tumour suppressor gene'.\n"
        "- Build the explanation around ONE concrete everyday analogy (a brake, a photocopier "
        "jamming, a thermostat) and carry it through.\n"
        "- Convert every number into a plain comparison: '3.2-fold' becomes 'more than three "
        "times as many'. Drop p-values, confidence intervals and units entirely.\n"
        "- Never assume the reader knows what a cell, gene, molecule or control group is.\n"
        "- Short sentences. Nothing a friend could not follow out loud."
    ),
    "Student": (
        "AUDIENCE: an undergraduate science student with general biology, chemistry and physics "
        "literacy, but no knowledge of this particular subfield.\n"
        "WHAT TO DO:\n"
        "- Use the real technical terms - they need to learn them - and define each briefly in "
        "parentheses the first time it appears.\n"
        "- CONNECT the finding to concepts a student already knows from a first- or second-year "
        "course: the cell cycle, the central dogma, enzyme kinetics, statistical significance, "
        "conservation laws. Explicitly name that link, e.g. 'this is the same checkpoint you meet "
        "when studying the cell cycle'.\n"
        "- Keep the key numbers and say plainly what each one means.\n"
        "- Assume cell, gene, molecule, experiment and control group need no explanation.\n"
        "- Register of a good textbook, not a news article. No everyday analogies."
    ),
    "Advanced": (
        "AUDIENCE: a practising researcher reading outside their own specialism.\n"
        "WHAT TO DO:\n"
        "- PRESERVE the science completely. Keep every technical term, metric, effect size, "
        "statistic and caveat exactly as precise as the source. Do NOT substitute simpler words "
        "for technical ones.\n"
        "- What you simplify is STRUCTURE, not content: reorganise into a clear logical order, "
        "break dense multi-clause sentences into shorter ones, and put the main finding first.\n"
        "- Expand subfield-specific acronyms and shorthand on first use, without dumbing them down.\n"
        "- State why the design or method is appropriate, and name any limitation the text itself "
        "acknowledges.\n"
        "- Absolutely no everyday analogies, and no talking down to the reader."
    ),
}

EXAMPLE_ABSTRACT = (
    "Targeted knockout of TP53 in HEK293T cells via CRISPR-Cas9 ribonucleoprotein delivery "
    "yielded a 3.2-fold increase in proliferative index (p<0.001) relative to isogenic controls. "
    "Transcriptomic profiling revealed concomitant upregulation of MKI67 and CCNB1, alongside "
    "attenuated expression of CDKN1A. These data are consistent with abrogation of the G1/S "
    "checkpoint and implicate p53 loss as a permissive event in the acquisition of a "
    "hyperproliferative phenotype in vitro."
)

EXAMPLE_2 = (
    "We performed a randomised, double-blind, placebo-controlled trial of a GLP-1 receptor agonist "
    "in 812 adults with obesity and prediabetes. At 68 weeks, mean body weight change from baseline "
    "was -14.9% in the treatment arm versus -2.4% with placebo (estimated treatment difference "
    "-12.4 percentage points; 95% CI -13.4 to -11.5; p<0.001). Gastrointestinal adverse events were "
    "more frequent with treatment and were typically transient and mild to moderate in severity."
)

EXAMPLE_3 = (
    "Metagenomic shotgun sequencing of 214 faecal samples identified a significant depletion of "
    "Faecalibacterium prausnitzii in patients with active inflammatory bowel disease compared with "
    "healthy controls (LDA score >3.5, q<0.05). Functional pathway analysis indicated reduced "
    "abundance of butyrate biosynthesis modules. Alpha diversity, measured by the Shannon index, was "
    "significantly lower in the disease cohort, consistent with dysbiosis."
)

# Deliberately outside biology, so the tool visibly is not tuned to one field.
EXAMPLE_4 = (
    "We report the observation of a quantised Hall conductance plateau in a monolayer graphene "
    "heterostructure encapsulated in hexagonal boron nitride. Magnetotransport measurements at 1.6 K "
    "and fields up to 12 T reveal longitudinal resistivity minima coincident with Hall plateaux at "
    "filling factors nu = +/-2, +/-6 and +/-10, consistent with the four-fold spin and valley "
    "degeneracy of Dirac fermions. Extracted carrier mobilities exceed 100,000 cm^2/Vs, and the "
    "temperature dependence of the plateau width yields an activation gap of the order of 10 meV at "
    "nu = 2. These results indicate that substrate-induced disorder, rather than intrinsic "
    "scattering, limits transport quality in comparable devices."
)


def build_messages(text, level):
    system = BASE_RULES + "\n\n" + LEVELS.get(level, LEVELS["Student"])
    user = (
        "Explain the following text for the specified audience, following every rule.\n\n"
        "--- TEXT START ---\n" + text.strip() + "\n--- TEXT END ---"
    )
    return [{"role": "system", "content": system}, {"role": "user", "content": user}]


def scrub(s):
    """Defensive: strip reasoning tags if a model ever leaks them."""
    s = re.sub(r"<think>.*?</think>", "", s, flags=re.DOTALL | re.IGNORECASE)
    return s.replace("<think>", "").replace("</think>", "")


def explain(text, level):
    """Streaming generator -> (explanation, status)."""
    text = (text or "").strip()

    if not text:
        yield "", "Paste an abstract above, then press **Explain**."
        return
    if len(text) < MIN_CHARS:
        yield "", "That's very short. Paste at least a couple of sentences."
        return
    if len(text) > MAX_CHARS:
        yield "", "That's " + format(len(text), ",") + " characters. Please trim it to under " + format(MAX_CHARS, ",") + "."
        return

    api_key = os.environ.get("NVIDIA_API_KEY")
    if not api_key:
        _log("NVIDIA_API_KEY is not set")
        yield "", (
            SERVICE_DOWN if HOSTED else
            "**No API key found.** Set `NVIDIA_API_KEY` in your terminal, then restart the app. "
            "In PowerShell: `$env:NVIDIA_API_KEY = \"nvapi-...\"`"
        )
        return
    if not api_key.startswith("nvapi-"):
        _log("NVIDIA_API_KEY has an unexpected prefix")
        yield "", (
            SERVICE_DOWN if HOSTED else
            "**That key doesn't look right.** NVIDIA API keys start with `nvapi-`."
        )
        return

    client = OpenAI(base_url=BASE_URL, api_key=api_key, timeout=90.0)
    busy = "Generating with `" + MODEL_ID + "` ..."

    for attempt in range(MAX_ATTEMPTS):
        streamed = False
        try:
            yield "", busy
            stream = client.chat.completions.create(
                model=MODEL_ID,
                messages=build_messages(text, level),
                temperature=0.3,
                top_p=0.95,
                max_tokens=700,
                stream=True,
                extra_body=NO_THINKING,
            )

            buf = ""
            for chunk in stream:
                if not chunk.choices:
                    continue
                piece = getattr(chunk.choices[0].delta, "content", None)
                if piece:
                    buf += piece
                    streamed = True
                    yield scrub(buf), busy

            if not buf.strip():
                raise RuntimeError("empty response")

            yield scrub(buf).strip(), "Done - " + level + " level, generated by `" + MODEL_ID + "`."
            return

        except Exception as e:
            msg = str(e)
            low = msg.lower()

            # NVIDIA's hosted endpoint intermittently returns "Service temporarily
            # overloaded". Retry quietly rather than showing an error mid-demo.
            transient = any(
                k in low
                for k in ("overload", "429", "rate limit", "502", "503", "504",
                          "timeout", "timed out", "empty response", "connection error")
            )
            if transient and not streamed and attempt < MAX_ATTEMPTS - 1:
                delay = RETRY_DELAYS[min(attempt, len(RETRY_DELAYS) - 1)]
                yield "", (
                    "The service is busy - retrying ("
                    + str(attempt + 2) + "/" + str(MAX_ATTEMPTS) + ") ..."
                )
                time.sleep(delay)
                continue

            # Full detail goes to the server log for the operator, never to the UI.
            _log(f"{type(e).__name__}: {msg[:300]}")

            # NVIDIA returns 403 (not 401) for a malformed or revoked key.
            if ("401" in msg or "403" in msg or "unauthorized" in low
                    or "forbidden" in low or "permissiondenied" in low
                    or "invalid api key" in low):
                hint = SERVICE_DOWN if HOSTED else (
                    "**API key rejected.** NVIDIA refused the key. Generate a fresh one at "
                    "build.nvidia.com, then set NVIDIA_API_KEY again and restart the app."
                )
            elif "404" in msg or "not found" in low:
                hint = SERVICE_DOWN if HOSTED else (
                    "**Model `" + MODEL_ID + "` is not available to this account (404).** "
                    "Open build.nvidia.com, pick a Nemotron model you do have access to, "
                    "and change MODEL_ID at the top of app.py."
                )
            elif transient:
                hint = (
                    "**The service is busy right now.** Please press Explain to try again."
                )
            elif "connect" in low:
                hint = (
                    "**Could not reach the explanation service.** Please check your "
                    "connection and try again."
                )
            else:
                # Never surface the exception type or message to a public visitor.
                hint = SERVICE_DOWN if HOSTED else (
                    "**Something went wrong.** `" + type(e).__name__ + ": " + msg[:300] + "`"
                )
            yield "", hint
            return


# --------------------------------------------------------------------------
# VISITOR COUNTER
# --------------------------------------------------------------------------
# Counts unique visitors. Raw IP addresses are NEVER written to disk - each IP
# is salted and hashed, and only the hash is stored. That gives uniqueness
# without keeping personal data.
_VISITOR_LOCK = threading.Lock()
_VISITOR_SALT = "research-paper-explainer-v1"


def _visitor_file():
    """Azure App Service keeps /home across restarts and redeploys."""
    if os.environ.get("WEBSITE_SITE_NAME"):
        base = "/home/data"
    else:
        base = os.path.dirname(os.path.abspath(__file__))
    try:
        os.makedirs(base, exist_ok=True)
    except Exception:
        base = tempfile.gettempdir()
    return os.path.join(base, "visitors.json")


def _client_ip(request):
    """Real client IP. Behind Azure's proxy it arrives in X-Forwarded-For."""
    if request is None:
        return None
    ip = ""
    try:
        ip = (request.headers.get("x-forwarded-for") or "").split(",")[0].strip()
    except Exception:
        pass
    if not ip:
        ip = getattr(getattr(request, "client", None), "host", "") or ""
    # Azure appends :port to IPv4 entries; IPv6 is left alone.
    if re.match(r"^\d{1,3}(\.\d{1,3}){3}:\d+$", ip):
        ip = ip.rsplit(":", 1)[0]
    return ip or None


def count_visitor(request):
    """Record this visitor if new, and return the unique total."""
    path = _visitor_file()
    with _VISITOR_LOCK:
        seen = set()
        try:
            with open(path, "r", encoding="utf-8") as f:
                seen = set(json.load(f).get("hashes", []))
        except Exception:
            pass

        ip = _client_ip(request)
        if ip:
            digest = hashlib.sha256((_VISITOR_SALT + ip).encode()).hexdigest()[:16]
            if digest not in seen:
                seen.add(digest)
                try:
                    with open(path, "w", encoding="utf-8") as f:
                        json.dump({"total": len(seen), "hashes": sorted(seen)}, f)
                except Exception:
                    pass
        return len(seen)


def last_updated():
    """Deploy time, taken from this file's timestamp. UTC, to the minute."""
    try:
        ts = os.path.getmtime(os.path.abspath(__file__))
        return datetime.fromtimestamp(ts, tz=timezone.utc).strftime(
            "%d %B %Y at %H:%M UTC"
        )
    except Exception:
        return "September 2026"


# --------------------------------------------------------------------------
# UI
# --------------------------------------------------------------------------
# NOTE: colours use Gradio's own CSS variables rather than fixed hex values.
# Hardcoding a light background here makes the explanation invisible when the
# browser or OS is in dark mode (white text on a white panel).
CSS = """
.gradio-container { max-width: 1080px !important; margin: 0 auto !important; }
#hdr { text-align: center; padding: 8px 0 2px 0; }
#hdr h1 {
  font-size: 2rem; margin: 0 0 6px 0; letter-spacing: -0.02em;
  color: var(--body-text-color);
}
#hdr p { color: var(--body-text-color-subdued); margin: 0; font-size: 0.98rem; }
#badge {
  display: inline-block; margin-top: 10px; padding: 4px 12px; border-radius: 999px;
  background: #76B900; color: #ffffff; font-size: 0.76rem; font-weight: 600;
  letter-spacing: 0.04em;
}
#out {
  min-height: 240px;
  background: var(--background-fill-secondary);
  color: var(--body-text-color);
  border: 1px solid var(--border-color-primary);
  border-radius: 10px; padding: 18px 20px; font-size: 1.05rem; line-height: 1.72;
}
#out p { color: var(--body-text-color); }
#status { color: var(--body-text-color-subdued); font-size: 0.86rem; min-height: 20px; }
footer { display: none !important; }

#site-footer {
  margin-top: 26px; padding-top: 16px;
  border-top: 1px solid var(--border-color-primary);
  text-align: center; line-height: 1.85;
  color: var(--body-text-color-subdued);
}
#site-footer .f-stats { font-size: 0.86rem; }
#site-footer .f-credits { font-size: 0.8rem; margin-top: 7px; }
#site-footer .f-copy {
  font-size: 0.76rem; margin-top: 7px; opacity: 0.8;
}
#site-footer .f-dot { margin: 0 7px; opacity: 0.5; }
#site-footer a { color: #76B900; text-decoration: none; }
#site-footer a:hover { text-decoration: underline; }

#site-footer .f-social {
  display: flex; justify-content: center; align-items: center;
  gap: 10px; flex-wrap: wrap; margin-bottom: 12px;
}
#site-footer .f-social a {
  display: inline-flex; align-items: center; gap: 7px;
  padding: 6px 13px; border-radius: 999px;
  border: 1px solid var(--border-color-primary);
  color: var(--body-text-color); font-size: 0.84rem;
  transition: border-color .15s ease, color .15s ease;
}
#site-footer .f-social a:hover {
  border-color: #76B900; color: #76B900; text-decoration: none;
}
#site-footer .f-social svg { flex: none; }
#caption {
  margin-top: 8px; font-size: 0.82rem;
  color: var(--body-text-color-subdued);
}
#char-count {
  margin: 4px 2px 0 2px; font-size: 0.78rem; text-align: right;
  color: var(--body-text-color-subdued);
}
#no-invent {
  margin: 8px 2px 0 2px; font-size: 0.78rem; line-height: 1.5;
  color: var(--body-text-color-subdued);
}
#out-head { align-items: center; gap: 10px; }
#out-head h3 { margin: 0; }
#copy-btn { min-width: 140px; }
#about-box {
  margin-top: 22px; padding: 16px 18px;
  border: 1px solid var(--border-color-primary);
  border-radius: 10px;
  background: var(--background-fill-secondary);
}
#about-box .ab-title {
  font-weight: 600; font-size: 0.95rem; margin-bottom: 12px;
  color: var(--body-text-color);
}
#about-box .ab-grid {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(230px, 1fr));
  gap: 14px;
}
#about-box .ab-grid > div {
  font-size: 0.83rem; line-height: 1.6;
  color: var(--body-text-color-subdued);
}
#about-box .ab-h {
  display: block; font-weight: 600; margin-bottom: 3px;
  color: var(--body-text-color);
}
#about-box .ab-foot {
  margin-top: 13px; padding-top: 11px;
  border-top: 1px solid var(--border-color-primary);
  font-size: 0.79rem; line-height: 1.55;
  color: var(--body-text-color-subdued);
}
#about-body { font-size: 0.97rem; line-height: 1.7; }
#about-body h2 { margin-top: 26px; }
#about-body table { width: 100%; }
"""

HEADER = """
<div id="hdr">
  <h1>Research Paper Explainer</h1>
  <p>Paste a dense abstract. Get it back in language you can actually use.</p>
  <div id="badge">POWERED BY NVIDIA NEMOTRON</div>
  <div id="caption">Powered by NVIDIA Nemotron &mdash; via build.nvidia.com</div>
</div>
"""

# Static UI text. Never generated by the model.
NO_INVENTION_NOTE = (
    "<p id='no-invent'>Explanation generated only from the text you provided. "
    "No external facts added.</p>"
)

# Visible on the main tab, not hidden away on a separate page. States plainly
# what the tool does and what it does not collect.
ABOUT_BOX = """
<div id="about-box">
  <div class="ab-title">About this tool &amp; your data</div>
  <div class="ab-grid">
    <div>
      <span class="ab-h">What it is</span>
      A free tool that rewrites dense scientific abstracts into plain language at
      three reading levels, built by a biotechnology student to help other students
      get past jargon.
    </div>
    <div>
      <span class="ab-h">What it does</span>
      The text you paste is sent over an encrypted connection to NVIDIA's Nemotron
      model at build.nvidia.com, and the explanation is returned to your screen.
      That is the whole process.
    </div>
    <div>
      <span class="ab-h">What it does NOT do</span>
      No accounts. No sign-in. No passwords. It never asks for personal, financial
      or contact details. It does not store the text you paste, does not keep your
      explanations, and runs no analytics, tracking or advertising code.
    </div>
  </div>
  <div class="ab-foot">
    The only thing recorded is an anonymous count of unique visitors, stored as a
    one-way hash so no IP address is ever written to disk.
  </div>
</div>
"""

# Gradio 6 removed show_copy_button from Textbox and Markdown, so the copy
# action is done in the browser. Falls back to execCommand where the async
# clipboard API is unavailable (non-HTTPS origins).
COPY_JS = """
() => {
  const el = document.querySelector('#out');
  const txt = el ? el.innerText.trim() : '';
  const btn = document.querySelector('#copy-btn');
  const flash = (msg) => {
    if (!btn) return;
    if (!btn.dataset.orig) btn.dataset.orig = btn.textContent;
    btn.textContent = msg;
    clearTimeout(btn._resetTimer);
    btn._resetTimer = setTimeout(() => { btn.textContent = btn.dataset.orig; }, 1600);
  };
  if (!txt) { flash('Nothing to copy'); return; }
  // Fallback for any clipboard failure: permission denied, insecure origin,
  // or the document not being focused.
  const legacy = () => {
    try {
      const ta = document.createElement('textarea');
      ta.value = txt;
      ta.style.position = 'fixed';
      ta.style.top = '-1000px';
      document.body.appendChild(ta);
      ta.focus();
      ta.select();
      const ok = document.execCommand('copy');
      document.body.removeChild(ta);
      flash(ok ? 'Copied' : 'Select and press Ctrl+C');
    } catch (e) {
      flash('Select and press Ctrl+C');
    }
  };
  if (navigator.clipboard && window.isSecureContext) {
    navigator.clipboard.writeText(txt).then(() => flash('Copied')).catch(legacy);
  } else {
    legacy();
  }
}
"""

# Live character counter, wired client-side so typing costs no server round trip.
COUNTER_JS = """
() => {
  const LIMIT = __LIMIT__;
  let last = -1;
  const sync = () => {
    const ta = document.querySelector('#inp textarea');
    const out = document.querySelector('#char-count');
    if (!ta || !out) return;
    const n = ta.value.length;
    if (n === last) return;
    last = n;
    out.textContent = n.toLocaleString() + ' / ' + LIMIT.toLocaleString() + ' characters';
    out.style.color = n > LIMIT * 0.9 ? '#d97706' : '';
  };
  const wire = () => {
    const ta = document.querySelector('#inp textarea');
    if (!ta || ta.dataset.counterWired === '1') return !!ta;
    ta.dataset.counterWired = '1';
    ta.addEventListener('input', sync);
    return true;
  };
  wire();
  sync();
  // Gradio fills the box programmatically when an example or Clear is used,
  // which fires no input event, so poll as well as listen.
  setInterval(() => { wire(); sync(); }, 400);
}
"""

FOOTNOTE = (
    "<p style='text-align:center;color:var(--body-text-color-subdued);"
    "font-size:0.8rem;margin-top:16px'>"
    "Inference-only. The model is instructed to use only the text you paste - "
    "always check the explanation against the original paper.</p>"
)

GITHUB_URL = "https://github.com/vipin839/research-paper-explainer"
GITHUB_PROFILE = "https://github.com/vipin839"
LINKEDIN_URL = "https://www.linkedin.com/in/s-vipin/"
CONTACT_EMAIL = "sainivipin839@gmail.com"

# Inline SVG marks (simple-icons paths). Inlined rather than loaded from a CDN
# so the footer never depends on an external request that could fail.
_ICON_GITHUB = (
    '<svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor" '
    'aria-hidden="true"><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 '
    '9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724'
    '-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729'
    '.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998'
    '.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 '
    '1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 '
    '1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23'
    '.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625'
    '-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21'
    '.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>'
)
_ICON_LINKEDIN = (
    '<svg viewBox="0 0 24 24" width="16" height="16" fill="currentColor" '
    'aria-hidden="true"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037'
    '-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046'
    'c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 '
    '7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 '
    '2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h'
    '3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 '
    '1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h'
    '.003z"/></svg>'
)
_ICON_MAIL = (
    '<svg viewBox="0 0 24 24" width="16" height="16" fill="none" '
    'stroke="currentColor" stroke-width="2" stroke-linecap="round" '
    'stroke-linejoin="round" aria-hidden="true">'
    '<rect x="2" y="4" width="20" height="16" rx="2"/>'
    '<path d="m22 7-10 6L2 7"/></svg>'
)


def footer_html(visitors):
    """Site footer: last updated, unique visitors, socials, credits."""
    return f"""
<div id="site-footer">
  <div class="f-social">
    <a href="{LINKEDIN_URL}" target="_blank" rel="noopener" title="LinkedIn">
      {_ICON_LINKEDIN}<span>LinkedIn</span></a>
    <a href="{GITHUB_PROFILE}" target="_blank" rel="noopener" title="GitHub">
      {_ICON_GITHUB}<span>GitHub</span></a>
    <a href="mailto:{CONTACT_EMAIL}" title="Email">
      {_ICON_MAIL}<span>{CONTACT_EMAIL}</span></a>
  </div>
  <div class="f-stats">
    <span><strong>Last updated:</strong> {last_updated()}</span>
    <span class="f-dot">&middot;</span>
    <span><strong>Unique visitors:</strong> {visitors:,}</span>
  </div>
  <div class="f-credits">
    Model inference by <strong>NVIDIA Nemotron</strong> via the
    <a href="https://build.nvidia.com" target="_blank" rel="noopener">NVIDIA hosted API</a>
    &middot; Interface built with <a href="https://gradio.app" target="_blank" rel="noopener">Gradio</a>
    &middot; Deployed on <strong>Microsoft Azure App Service</strong>
    &middot; Source on <a href="{GITHUB_URL}" target="_blank" rel="noopener">GitHub</a>
    &middot; Developed with <strong>Claude Code</strong> (Anthropic)
  </div>
  <div class="f-copy">
    Built by Vipin &middot; Biotechnology &amp; Bioinformatics &middot;
    For the NVIDIA GTC Golden Ticket Developer Contest
  </div>
</div>
"""


ABOUT_MD = f"""
## About this tool

**Research Paper Explainer** turns a dense scientific abstract into a plain-language
explanation pitched at the reading level you choose. It was built by a biotechnology
and bioinformatics student for the problem students actually have: not understanding
the science, but decoding the vocabulary wrapped around it.

Paste an abstract, pick **Beginner**, **Student** or **Advanced**, and the tool
rewrites it — defining every unavoidable technical term inline, in parentheses, as it
goes. You learn the vocabulary instead of skipping past it.

---

## How it works

```
You paste an abstract  ->  the app builds a system prompt
                           (8 rules + your chosen audience)
                                    |
                                    v
                        openai Python client over HTTPS
                                    |
                                    v
                      NVIDIA hosted inference endpoint
                     nvidia/nemotron-3-super-120b-a12b
                                    |
                                    v
                    tokens stream back and fill the page live
```

Everything runs **inference-only**. No model is trained, fine-tuned, or downloaded.
The app is a thin, carefully-designed layer between a text box and a large language
model — the heavy computation happens on NVIDIA's hardware, not on this server.

---

## The NVIDIA model

This tool runs on **`nvidia/nemotron-3-super-120b-a12b`**, part of NVIDIA's
openly-published **Nemotron** family, accessed through NVIDIA's hosted API at
`integrate.api.nvidia.com`.

Two things about that endpoint shaped the build:

**It is OpenAI-API-compatible.** NVIDIA implements the same request and response
shape as the OpenAI API, so the standard `openai` Python package works by pointing it
at a different `base_url`. No custom HTTP code, and swapping providers later is a
one-line change.

**Nemotron 3 is a reasoning model.** By default it writes out a private train of
thought before answering — and that reasoning appears in the reply, so users would
read *"Okay, the user has given me a scientific statement..."* instead of their
explanation. The app disables it with
`extra_body={{"chat_template_kwargs": {{"thinking": false}}}}`, which was found by
testing rather than from documentation.

The model choice itself came from testing every Nemotron the account could reach.
This one answered in about two seconds with clean output; a smaller variant degraded
into repeated characters once reasoning was disabled.

---

## Tech stack

| Layer | Choice | Why |
|---|---|---|
| Model | `nvidia/nemotron-3-super-120b-a12b` | Fastest clean responder tested (~2s to first token) |
| Inference | NVIDIA hosted API | No local GPU needed; genuinely inference-only |
| Client | `openai` Python package | The endpoint is OpenAI-compatible, so no custom HTTP |
| Interface | Gradio | Python-only UI with native streaming support |
| Hosting | Azure App Service (Linux, B1) | Runs a persistent process, which streaming requires |
| CI/CD | GitHub Actions | Every push to `main` redeploys automatically |
| Built with | Claude Code (Anthropic) | Pair-programmed, tested and debugged |

---

## How to use it

1. **Paste** a scientific abstract into the box on the Explain tab
2. **Choose a reading level**
   - **Beginner** — no science background; jargon avoided, analogies allowed
   - **Student** — undergraduate; knows general biology, not this subfield
   - **Advanced** — a researcher from a different field; precision kept, shorthand unpacked
3. **Press Explain** and watch the explanation stream in
4. Or click one of the three built-in examples to try it instantly

Each explanation is 4–6 sentences and always ends with one sentence on why the
finding matters practically.

---

## Accuracy and limits

The prompt is written explicitly against fabrication: the model is instructed to use
**only** the text you paste and never introduce outside facts. That is the real risk
when an AI explains research, and it received more attention than the interface did.

Even so, be aware:

- Fabrication is **reduced by the prompt, not eliminated**. Always check against the
  original paper.
- The 4–6 sentence rule is an *instruction*, not a hard constraint.
- Input is capped at 12,000 characters.
- NVIDIA's endpoint is rate-limited and occasionally busy; the app retries transient
  failures automatically.
- It reads pasted text only — no PDF upload, no figures, no references.

---

## Links

- **Source code:** [{GITHUB_URL}]({GITHUB_URL})
- **Contact:** [{CONTACT_EMAIL}](mailto:{CONTACT_EMAIL})
- **NVIDIA model catalogue:** [build.nvidia.com](https://build.nvidia.com)

Built for the **NVIDIA GTC Golden Ticket Developer Contest**.
"""

with gr.Blocks(title="Research Paper Explainer") as demo:

    gr.HTML(HEADER)

    with gr.Tabs():
        with gr.Tab("Explain"):
            with gr.Row():
                with gr.Column(scale=1):
                    inp = gr.Textbox(
                        label="Abstract or paragraph",
                        placeholder="Paste a scientific abstract here...",
                        lines=13,
                        value=EXAMPLE_ABSTRACT,
                        elem_id="inp",
                        max_length=MAX_CHARS,
                        info=f"Up to {MAX_CHARS:,} characters - about a full paper.",
                    )
                    gr.HTML(f"<p id='char-count'>0 / {MAX_CHARS:,} characters</p>")
                    level = gr.Radio(
                        choices=["Beginner", "Student", "Advanced"],
                        value="Student",
                        label="Reading level",
                        info="Who is this explanation for?",
                    )
                    with gr.Row():
                        go = gr.Button("Explain", variant="primary", scale=3)
                        clear = gr.Button("Clear", scale=1)

                with gr.Column(scale=1):
                    with gr.Row(elem_id="out-head"):
                        gr.Markdown("### Plain-language explanation")
                        copy_btn = gr.Button(
                            "Copy explanation", size="sm", elem_id="copy-btn", scale=0
                        )
                    out = gr.Markdown(value="", elem_id="out")
                    gr.HTML(NO_INVENTION_NOTE)
                    status = gr.Markdown(value="Ready.", elem_id="status")

            gr.Markdown("#### Try another example")
            gr.Examples(
                examples=[
                    [EXAMPLE_ABSTRACT, "Student"],
                    [EXAMPLE_2, "Beginner"],
                    [EXAMPLE_3, "Advanced"],
                    [EXAMPLE_4, "Student"],
                ],
                inputs=[inp, level],
                example_labels=[
                    "Cell biology - CRISPR TP53 knockout",
                    "Clinical trial - GLP-1 weight loss",
                    "Microbiome - gut bacteria in IBD",
                    "Physics - graphene quantum Hall effect",
                ],
            )

            gr.HTML(ABOUT_BOX)
            gr.HTML(FOOTNOTE)

        with gr.Tab("About"):
            gr.Markdown(ABOUT_MD, elem_id="about-body")

    site_footer = gr.HTML(footer_html(0))

    go.click(explain, inputs=[inp, level], outputs=[out, status])
    inp.submit(explain, inputs=[inp, level], outputs=[out, status])
    clear.click(lambda: ("", "", "Ready."), outputs=[inp, out, status])
    copy_btn.click(fn=None, inputs=None, outputs=None, js=COPY_JS)

    def _on_load(request: gr.Request):
        return footer_html(count_visitor(request))

    demo.load(_on_load, inputs=None, outputs=[site_footer])
    demo.load(fn=None, inputs=None, outputs=None,
              js=COUNTER_JS.replace("__LIMIT__", str(MAX_CHARS)))


if __name__ == "__main__":
    # Detect managed hosts by the environment variables they set:
    #   Hugging Face Spaces -> SPACE_ID
    #   Azure App Service   -> WEBSITE_SITE_NAME
    # On any of them there is no browser to open, no share tunnel needed, and
    # the server must bind 0.0.0.0 so the platform's proxy can reach it.
    on_spaces = bool(os.environ.get("SPACE_ID"))
    on_azure = bool(os.environ.get("WEBSITE_SITE_NAME"))
    hosted = on_spaces or on_azure

    # Azure App Service injects the port to listen on as PORT.
    port = os.environ.get("PORT") or os.environ.get("GRADIO_SERVER_PORT")
    try:
        port = int(port) if port else None
    except ValueError:
        port = None

    host = os.environ.get("GRADIO_SERVER_NAME") or ("0.0.0.0" if hosted else "127.0.0.1")

    if not os.environ.get("NVIDIA_API_KEY"):
        print("")
        print("  WARNING: NVIDIA_API_KEY is not set. The UI will load but calls will fail.")
        if on_spaces:
            print("  On Spaces: add it under Settings -> Variables and secrets.")
        elif on_azure:
            print("  On Azure: add it under Settings -> Environment variables.")
        else:
            print('  PowerShell:  $env:NVIDIA_API_KEY = "nvapi-..."')
        print("")
    else:
        print("")
        print("  API key detected. Model: " + MODEL_ID)
        print("  Binding " + host + ":" + str(port or 7860))
        print("")

    demo.queue().launch(
        theme=gr.themes.Soft(primary_hue="green", neutral_hue="slate"),
        css=CSS,
        share=(not hosted) and os.environ.get("GRADIO_SHARE", "").lower() in ("1", "true", "yes"),
        inbrowser=not hosted,
        server_name=host,
        server_port=port,
    )
